# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\solar\Desktop\GestionAle1\Gest\views\ui\addcli.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchedaClienteView(object):
    def setupUi(self, SchedaClienteView):
        SchedaClienteView.setObjectName("SchedaClienteView")
        SchedaClienteView.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(SchedaClienteView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditDescrizione = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDescrizione.setObjectName("lineEditDescrizione")
        self.verticalLayout.addWidget(self.lineEditDescrizione)
        self.btnAddImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddImage.setObjectName("btnAddImage")
        self.verticalLayout.addWidget(self.btnAddImage)
        self.listWidgetImages = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetImages.setObjectName("listWidgetImages")
        self.verticalLayout.addWidget(self.listWidgetImages)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SchedaClienteView)
        QtCore.QMetaObject.connectSlotsByName(SchedaClienteView)

    def retranslateUi(self, SchedaClienteView):
        _translate = QtCore.QCoreApplication.translate
        SchedaClienteView.setWindowTitle(_translate("SchedaClienteView", "Inserisci Scheda Cliente"))
        self.lineEditDescrizione.setPlaceholderText(_translate("SchedaClienteView", "Descrizione"))
        self.btnAddImage.setText(_translate("SchedaClienteView", "Aggiungi Immagine"))
