# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\solar\Desktop\GestionAle1\Gest\views\ui\dashboard1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(217, 208, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 791, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAltro_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.btnAltro_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Desktop/GestionAle1/Gest/resources/icons/Progetto senza titolo (14).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAltro_3.setIcon(icon)
        self.btnAltro_3.setIconSize(QtCore.QSize(100, 100))
        self.btnAltro_3.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnAltro_3.setObjectName("btnAltro_3")
        self.gridLayout.addWidget(self.btnAltro_3, 0, 4, 1, 1)
        self.btnAltro_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.btnAltro_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Desktop/GestionAle1/Gest/resources/icons/+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAltro_5.setIcon(icon1)
        self.btnAltro_5.setIconSize(QtCore.QSize(100, 100))
        self.btnAltro_5.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnAltro_5.setObjectName("btnAltro_5")
        self.gridLayout.addWidget(self.btnAltro_5, 2, 1, 1, 1)
