# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\solar\Desktop\GestionAle1\Gest\views\ui\minidash1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(217, 208, 255);")
        MainWindow.setToolButtonStyle(QtCore.Qt.Qt::ToolButtonStyle::ToolButtonIconOnly)
        MainWindow.setTabShape(QtCore.Qt.QTabWidget::TabShape::Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 791, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAgenda = QtWidgets.QToolButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(20)
        font.setItalic(True)
        self.btnAgenda.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Progetto senza titolo (12).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgenda.setIcon(icon)
        self.btnAgenda.setIconSize(QtCore.QSize(130, 180))
        self.btnAgenda.setToolButtonStyle(QtCore.Qt.Qt::ToolButtonStyle::ToolButtonTextUnderIcon)
        self.btnAgenda.setObjectName("btnAgenda")
        self.gridLayout.addWidget(self.btnAgenda, 0, 0, 1, 1)
        self.btnClienti = QtWidgets.QToolButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(20)
        font.setItalic(True)
        self.btnClienti.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Progetto senza titolo (9).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClienti.setIcon(icon1)
        self.btnClienti.setIconSize(QtCore.QSize(130, 180))
        self.btnClienti.setToolButtonStyle(QtCore.Qt.Qt::ToolButtonStyle::ToolButtonTextUnderIcon)
        self.btnClienti.setObjectName("btnClienti")
        self.gridLayout.addWidget(self.btnClienti, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnAgenda.clicked.connect(MainWindow.on_btnAgenda_clicked) # type: ignore
        self.btnClienti.clicked.connect(MainWindow.on_btnClienti_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAgenda.setText(_translate("MainWindow", "Agenda"))
        self.btnClienti.setText(_translate("MainWindow", "Clienti"))
import resources_rc
