# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\solar\Desktop\GestionAle1\Gest\views\ui\miniclienti.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setItalic(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 901, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(18)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnAddClient = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(11)
        font.setItalic(True)
        self.btnAddClient.setFont(font)
        self.btnAddClient.setObjectName("btnAddClient")
        self.horizontalLayout_4.addWidget(self.btnAddClient)
        self.btnViewClient = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(11)
        font.setItalic(True)
        self.btnViewClient.setFont(font)
        self.btnViewClient.setObjectName("btnViewClient")
        self.horizontalLayout_4.addWidget(self.btnViewClient)
        self.btnModClient = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(11)
        font.setItalic(True)
        self.btnModClient.setFont(font)
        self.btnModClient.setObjectName("btnModClient")
        self.horizontalLayout_4.addWidget(self.btnModClient)
        self.btnDelClient = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(11)
        font.setItalic(True)
        self.btnDelClient.setFont(font)
        self.btnDelClient.setObjectName("btnDelClient")
        self.horizontalLayout_4.addWidget(self.btnDelClient)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.gridLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
