# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\solar\Desktop\GestionAle1\Gest\views\ui\scheda_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchedaClienteView(object):
    def setupUi(self, SchedaClienteView):
        SchedaClienteView.setObjectName("SchedaClienteView")
        SchedaClienteView.resize(800, 544)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(11)
        font.setItalic(True)
        SchedaClienteView.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(SchedaClienteView)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 751, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(18)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inria Serif")
        font.setPointSize(20)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEditDescrizione = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEditDescrizione.setObjectName("plainTextEditDescrizione")
        self.verticalLayout_2.addWidget(self.plainTextEditDescrizione)
        self.listWidgetImages = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidgetImages.setObjectName("listWidgetImages")
        self.verticalLayout_2.addWidget(self.listWidgetImages)
        self.btnAddImage = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAddImage.setObjectName("btnAddImage")
        self.verticalLayout_2.addWidget(self.btnAddImage)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)

        self.retranslateUi(SchedaClienteView)
        QtCore.QMetaObject.connectSlotsByName(SchedaClienteView)

    def retranslateUi(self, SchedaClienteView):
        _translate = QtCore.QCoreApplication.translate
        SchedaClienteView.setWindowTitle(_translate("SchedaClienteView", "Inserisci Scheda Cliente"))
        self.label.setText(_translate("SchedaClienteView", "Scheda Cliente"))
        self.btnAddImage.setText(_translate("SchedaClienteView", "Aggiungi Immagine"))
